<img src="../Img/Python_SQL_PI.png" style="width:100%">

<a id = Home></a>
<br>
<p style="font-size:150%;text-align:center">Лекция 5. Библиотека SQLAlchemy и язык SQL-выражений</p>

<br><br>
7 апреля 2022 года, чт., В4/3501 (4-й Вешняковский проезд, 4)<br>
ПИ20-1, ПИ20-2, ПИ20-3, <br>

11 апреля 2022 года, пн., Щ38/512 (ул. Щербаковская, 38)<br>
ПИ20-4, ПИ20-5, ПИ20-6

Смирнов Михаил Викторович, доцент Департамента анализа данных и машинного обучения Финансового университета при Правительстве Российской Федерации. mvsmirnov@fa.ru

<p style="text-align:center">Москва - 2022</p>

При подготовке материалов учебных занятий использовались источники
- Essential SQLAlchemy: Mapping Python to Databases 2nd Edition. Jason Myers, Rick Copeland. O'Reilly Media, Inc. 2015.
- Астахова И.Ф., Мельников В.М., Толстобров А.П., Фертиков В.В. СУБД: язык SQL в примерах и задачах.—М.:ФИЗМАТЛИТ, 2009. — 168 с. — ISBN 978-5-9221-0816-4.
- Официальный сайт СУБД sqlite https://sqlite.org
- Официальный сайт библиотеки sqlalchemy https://www.sqlalchemy.org/
- Аналитический проект системы AirBnB http://insideairbnb.com/

<a id=Ref></a>

<p style="font-size:150%">Оглавление</p>

[Введение](#Intro)<br>
[5.1. Схема и типы данных](#T_5_1)<br>
[5.2. Вставка данных](#T_5_2)<br>
[5.3. Запросы к данным](#T_5_3)<br>
[5.4. Исключения и транзакции](#T_5_4)<br>
[5.5. Отображение](#T_5_5)<br>

<a id=T_1></a>
# Тема 1. Библиотека SQLAlchemy и язык SQL-выражений

<a id=Intro></a>
# Введение
[<= ](#Ref)||[ К оглавлению ](#Ref)||[ =>](#T_5_1)

## SQLAlchemy и язык SQL-выражений

SQLAlchemy - библиотека Пайтон, которая устраняет разрыв между реляционными базами данных и традиционным программированием. Хотя SQLAlchemy позволяет «опуститься» до необработанного SQL для выполнения запросов, она поощряет мышление более высокого уровня за счет более «питонического» и дружественного подхода к запросам и обновлению базы данных. SQLAlchemy используется для взаимодействия с широким спектром баз данных. Библиотека позволяет создавать модели данных и запросы в манере, напоминающей обычные классы и операторы Python.

Язык SQL-выражений (SQL Expression Language), называемый также Кор (Core, ядро) - это инструмент SQLAlchemy для представления общих операторов и выражений SQL в стиле Пайтон. Он ориентирован на фактическую схему базы данных и стандартизирован таким образом, что обеспечивает единообразный язык для большого числа серверных баз данных.

SQLAlchemy Core имеет представление, ориентированное на схему, таблицы, ключи и индексы, как и традиционный SQL. SQLAlchemy Core эффективен в отчетах, анализе и других применениях, где полезно иметь возможность жестко контролировать запрос или работать с немоделированными данными. Надежный пул соединений с базой данных и оптимизация набора результатов идеально подходят для работы с большими объемами данных.

## Кодирование

Работать с SQLAlchemy удобно в интерактивной среде "чтение-оценка-вывод" (read-evaluate-print-loop REPL), в такой, как интерактивный ноутбук iPython http://ipython.org/

Установка Юпитер Ноутбук
https://jupyter.readthedocs.io/en/latest/install/notebook-classic.html

Для освоения и работы с ноутбуком iPython, рекомендуется пакет программ Анаконда (Anaconda).

https://www.anaconda.com/products/individual

Анаконда содержит Пайтон, Юпитер ноутбук и другие часто используемые приложения для научных вычислений и обработки данных.

Порядок установки и запуска интерктивной среды Юпитер ноутбук

1. Загрузить Анаконда
2. Установить Анаконда
3. Запустить Юпитер ноутбук. Для этого использовать команду меню, либо консольную команду

    => jupyter notebook

## Установка SQLAlchemy

Библиотеку SQLAlchemy необходимо установить. Для этого в ячейке iPython выполним команду

`! pip install sqlalchemy`

Установка SQLAlchemy проводится один раз, перед первым использованием. В дальнейшем, независимо от начала и окончания сессии работы в iPython, повторной установки не требуется.

In [1]:
# ! pip install sqlalchemy

In [2]:
import sqlalchemy
sqlalchemy.__version__

'1.4.22'

## Установка драйверов баз данных

По **_умолчанию_** SQLAlchemy поддерживает базы данных в формате SQLite3. Для подключения к другим базам данных необходимы дополнительные драйверы.

- PostgreSQL. <br>Установка драйвера Psycopg: https://www.psycopg.org/
- MySQL (требуется версия MySQL  4.1  и выше)
- Другие

SQLAlchemy также можно использовать вместе с СУБД Firebird, Oracle, Sybase и Microsoft SQL Server. Пользовательское сообщество также предложило внешние диалекты для многих других баз данных, таких как IBM DB2, Informix, Amazon Redshift, EXASolution, SAP SQL Anywhere, Monet и многих других. Создание диалектов поддерживается SQLAlchemy.

In [3]:
# PostgreSQL
# ! pip install psycopg2

# MySQL
# ! pip  install  pymysql

## Соединение с базой данных

Чтобы подключиться к базе данных, нужно создать механизм (движок) SQLAlchemy. Механизм SQLAlchemy создает общий интерфейс с базой данных для выполнения операторов SQL.

SQLAlchemy предоставляет функцию для создания механизма с учетом *строки подключения* и, возможно, некоторых дополнительных именованных (keyword arguments) аргументов. Строка подключения может содержать:

- Тип базы данных (Postgres, MySQL, etc.);
- Диалект, если он отличается от установленного по умолчанию для конкретного типа базы данных (Psycopg2, PyMySQL и т. д.);
- Дополнительные данные аутентификации (имя пользователя и пароль);
- Расположение базы данных (файл или имя хоста сервера базы данных);
- Дополнительный порт сервера базы данных;
- Необязательное имя базы данных.

Строка подключения позволяют нам использовать конкретный файл или место хранения. В примере 1 определяется файл базы данных SQLite с именем <TT>listings.db</tt>:
- хранящийся в текущем каталоге;
- в памяти;
- с указанием полного пути к файлу (Unix и Windows). 

В Windows строка подключения будет иметь вид engine4; \\\ требуются для экранирования символа "слэш".

Функция <TT>create_engine</tt> возвращает экземпляр механизма SQLAlchemy.

In [4]:
# 0-1. Создание механизма SQLAlchemy со строкой подключения SQLite

import sqlalchemy
from sqlalchemy import create_engine

engine = create_engine('sqlite:///listings.db')
# engine2 = create_engine('sqlite:///:memory:')
# engine3 = create_engine('sqlite:////home/Airbnb/listings.db')
# engine4 = create_engine('sqlite:///c:\\Users\\Airbnb\\listings.db')

PostgreSQL<br>Пример 2. Cоздание механизма для локальной базы данных PostgreSQL с именем mydb

`
from sqlalchemy import create_engine
engine=create_engine('postgresql+psycopg2://username:password@localhost:5432/mydb')
`

MySQL. <br> Пример 3. Создание механизма для удаленной БД MySQL

`
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://username:password''@mysql01.mikhail.internal/listings', pool_recycle=3600)
`

Теперь, когда создан экземпляр механизма соединения с базой данных, мы можем начать использовать SQLAlchemy Core чтобы связать наше приложение с сервисами базы данных.

<a id=T_5_1></a>
# 5.1. Схема и типы данных
[<= ](#Intro)||[ К оглавлению ](#Ref)||[ =>](#T_5_2)

В процессе выполнения кода примеров этой темы нам понадобятся библиотеки

In [5]:
from sqlalchemy import (MetaData, Table, Column, Integer, Numeric, String, DateTime, 
                        Boolean, ForeignKey, create_engine, PrimaryKeyConstraint, 
                        UniqueConstraint, CheckConstraint, ForeignKeyConstraint,
                        Index, insert, BigInteger)
import pandas as pd
from datetime import datetime

В SQLAlchemy имеется четыре категории типов данных: 
- Универсальный 
- Стандартный SQL 
- Зависящий от поставщика 
- Определяется пользователем

Универсальная категория типов данных предназначена для сопоставления типов данных в Python и SQL.

In [6]:
import pandas as pd
pd.DataFrame(['BigInteger,int,BIGINT'.split(','),
              'Boolean,bool,BOOLEAN or SMALLINT'.split(','),
              'Date,datetime.date,DATE (SQLite: STRING)'.split(','),
              'DateTime,datetime.datetime,DATETIME (SQLite: STRING)'.split(','),
              'Enum,str,ENUM or VARCHAR'.split(','),
              'Float,float or Decimal,FLOAT or REAL'.split(','),
              'Integer,int,INTEGER'.split(','),
              'Interval,datetime.timedelta,INTERVAL or DATE from epoch'.split(','),
              'LargeBinary,byte,BLOB or BYTEA'.split(','),
              'Numeric,decimal.Decimal,NUMERIC or DECIMAL'.split(','),
              'Unicode,unicode,UNICODE or VARCHAR'.split(','),
              'Text,str,CLOB or TEXT'.split(','),
              'Time,datetime.time,DATETIME'.split(',')],
              columns='SQLAlchemy,Python,SQL'.split(','))

SQLAlchemy              Python                          SQL
0    BigInteger                 int                       BIGINT
1       Boolean                bool          BOOLEAN or SMALLINT
2          Date       datetime.date        DATE (SQLite: STRING)
3      DateTime   datetime.datetime    DATETIME (SQLite: STRING)
4          Enum                 str              ENUM or VARCHAR
5         Float    float or Decimal                FLOAT or REAL
6       Integer                 int                      INTEGER
7      Interval  datetime.timedelta  INTERVAL or DATE from epoch
8   LargeBinary                byte                BLOB or BYTEA
9       Numeric     decimal.Decimal           NUMERIC or DECIMAL
10      Unicode             unicode           UNICODE or VARCHAR
11         Text                 str                 CLOB or TEXT
12         Time       datetime.time                     DATETIME

Стандартные типы (например CHAR и NVARCHAR)  используются в случаях, когда универсальные типы не отвечают требованиям из-за конкретной структуры данных.

Типы, зависящие от поставщика. Пример: поле JSON в PostgreSQL.

<TT>fromsqlalchemy.dialects.postgresqlimport JSON</tt>

## Метаданные

Метаданные используются для связывания структуры базы данных. Метаданные полезно рассматривать как каталог объектов таблиц с дополнительной информацией о механизме и соединении. Метаданные необходимо импортировать и инициализировать. Инициализируем экземпляр объектов MetaData:

In [7]:
# 1-1

from sqlalchemy import MetaData
metadata = MetaData()

## Таблицы

Объекты таблиц инициализируются в SQLAlchemy Core путем вызова конструктора <TT>Table</tt> с именем таблицы и метаданными, аргументы считаются объектами столбцов. Столбцы создаются путем вызова `Column` с именем, типом и затем аргументами, которые представляют дополнительные конструкции и ограничения SQL. В примере 1-2 создадим таблицу, которая может использоваться для перечня объектов размещения гостиничного бизнеса airbnb: http://insideairbnb.com/get-the-data.html


In [8]:
# 1-2

listing=Table('listing',metadata,
            Column('listing_id',Integer(),primary_key=True),
            Column('listing_name',String(50),index=True),
            Column('listing_url',String(255)),
            Column('host_id',Integer()),
            Column('neighbourhood_id',Integer()),
            Column('amenities',String(300)),
            Column('property_type_id',Integer()),
            Column('room_type_id',Integer()),
            Column('bedrooms',Integer()),
            Column('beds',Integer()),
            Column('price',Numeric(7,2)),
            CheckConstraint('price >= 0.00', name='listing_price_positive'),
            ForeignKeyConstraint(['host_id'], ['host.host_id']),
            ForeignKeyConstraint(['neighbourhood_id'], ['neighbourhood.neighbourhood_id']),
            ForeignKeyConstraint(['property_type_id'], ['property_type.property_type_id']),
            ForeignKeyConstraint(['room_type_id'], ['room_type.room_type_id']),
            extend_existing=True)

In [9]:
pd.DataFrame({'En':['listing_id','listing_name','listing_url','host_id','neighbourhood_id',
                  'amenities','property_type_id','room_type_id','bedrooms','beds','price'],
            'Ru':['идентификатор объекта размещения','имя объекта размещения',
                  'адрес веб-страницы','идентификатор владельца',
                  'идентификатор местоположения','оборудование, удобства',
                  'тип собственности','тип помещения','число спален','число кроватей','цена']})

En                                Ru
0         listing_id  идентификатор объекта размещения
1       listing_name            имя объекта размещения
2        listing_url                адрес веб-страницы
3            host_id           идентификатор владельца
4   neighbourhood_id      идентификатор местоположения
5          amenities            оборудование, удобства
6   property_type_id                 тип собственности
7       room_type_id                     тип помещения
8           bedrooms                      число спален
9               beds                    число кроватей
10             price                              цена

### Дополнительные аргументы

Рассмотрим использование дополнительных аргументов <TT>nullable, unique, onupdate</tt>

In [10]:
# 1-3

user=Table('user',metadata,
            Column('user_id',Integer(),primary_key=True),
            Column('user_name',String(15),nullable=False,unique=True),
            Column('email_address',String(255),nullable=False),
            Column('phone',String(20),nullable=False),
            Column('password',String(25),nullable=False),
            Column('created_on',DateTime(),default=datetime.now),
            Column('updated_on',DateTime(),default=datetime.now,onupdate=datetime.now)
           )

### Ключи и ограничения

Ключи и ограничения задают с помощью объектов <TT>PrimaryKeyConstraint, UniqueConstraint, CheckConstraint</tt>

#### Первичный ключ
В примерах 1-2 и 1-3  столбцы `listing_id` и `user_id` объявлялись первичными ключами с помощью ключевого слова <TT>primary_key</tt>. Также, можно определить составной первичный ключ, присвоив параметру <TT>primary_key</tt> значение <TT>True</tt> для нескольких столбцов. Таким образом, ключ рассматривается как кортеж, в котором столбцы, помеченные как ключ, присутствуют в порядке, в котором они были определены в таблице. Первичные ключи также могут быть определены после столбцов в конструкторе таблицы, как показано в следующем фрагменте.

`user=Table('user',metadata,
            Column('user_name',String(15),nullable=False,unique=True),
            Column('email_address',String(255),nullable=False),
            Column('phone',String(20),nullable=False),
            Column('password',String(25),nullable=False),
            Column('created_on',DateTime(),default=datetime.now),
            Column('updated_on',DateTime(),default=datetime.now,onupdate=datetime.now),
            PrimaryKeyConstraint('user_id', name='user_pk'),
            extend_existing=True
           )`

#### Уникальность
Другое распространенное ограничение - ограничение уникальности, которое используется, чтобы гарантировать, что в данном поле значения не повторяются.

<TT>UniqueConstraint('user_name', name='uix_username')</tt>

#### Проверка значения
Этот тип ограничения используется, чтобы гарантировать, что данные, предоставленные для столбца, соответствуют набору критериев, определенных пользователем. В следующем фрагменте кода мы гарантируем, что <TT>price</tt> не может быть меньше 0,00:

<TT>CheckConstraint('price >= 0.00', name='listing_price_positive')</tt>

### Индексы

В примере 1-2 создан индекс для столбца *listing_name*. Когда индексы создаются, как показано в этом примере, они получают имена <TT>ix_listings_listing_name</tt>. Мы также можем определить индекс, используя явный тип конструкции. Можно обозначить несколько столбцов, разделив их запятой. Можно добавить аргумент ключевого слова <TT>unique = True</tt>, чтобы индекс был уникальным. При явном создании индексов они передаются в конструктор таблиц после столбцов. Чтобы имитировать указанный индекс явным способом, в конструктор <TT>Table</tt> требуется добавить <TT>Index('ix_listings_listing_name', 'listing_name')</tt>

Мы также можем создавать функциональные индексы для ситуаций, когда часто требуется запрос на основе нескольких полей БД. Например, если мы хотим искать по параметрам оборудования ("удобства") и цены в качестве объединенного элемента, можно определить функциональный индекс для оптимизации поиска:

In [11]:
Index('ix_am_price', listing.c.amenities, listing.c.price)

Index('ix_am_price', Column('amenities', String(length=300), table=<listing>), Column('price', Numeric(precision=7, scale=2), table=<listing>))

### Связи и внешние ключи
Тепрь, когда имеются пользователи и объекты размещения, необходимо обеспечить связи, позволяющие пользователям бронировать те или иные объекты. Рассмотрим схему данных.

<img src="../Img/listing_schema.png" width="560">

Создадим таблицы для заказов `order`, `line_item`, таблицу местоположений `neighbourhood`, таблицы типов собственности и комнат `property_type`, `room_type`.

In [12]:
# 1-4

order = Table('order', metadata,
               Column('order_id', Integer(),primary_key=True),
               Column('user_id', ForeignKey('user.user_id')),
               Column('confirmed', Boolean(),default=False),
               Column('order_price', Integer()),
               extend_existing=True
              )

In [13]:
# 1-5

line_item = Table('line_item', metadata,
                   Column('line_item_id', Integer(), primary_key=True),
                   Column('order_id', ForeignKey('order.order_id')),
                   Column('listing_id', ForeignKey('listing.listing_id')),
                   Column('item_start_date', DateTime()),
                   Column('item_end_date', DateTime()),
                   Column('item_price', Integer()),
                   extend_existing=True
                  )

In [14]:
# 1-6

neighbourhood=Table('neighbourhood',metadata,
                    Column('neighbourhood_id',Integer(),primary_key=True),
                    Column('neighbourhood_name',String(30)),
                   )

In [15]:
# 1-7

property_type=Table('property_type',metadata,
                    Column('property_type_id',Integer(),primary_key=True),
                    Column('property_type_name',String(30))
                   )

In [16]:
# 1-8

room_type=Table('room_type',metadata,
                Column('room_type_id',Integer(),primary_key=True),
                Column('room_type_name',String(30))
               )

In [17]:
# 1-9

host=Table('host',metadata,
           Column('host_id',Integer(),primary_key=True),
           Column('host_name',String(30))
          )

В примерах 1-4 и 1-5 внешние ключи задаются с помощью строки: <TT>'order.order_id'</tt>. Также существует явный способ задания ограничений по внешнему ключу: <TT>ForeignKeyConstraint(['order_id'], ['order.order_id'])</tt>

## Сохранение таблиц

Все таблицы и определения связаны с экземпляром метаданных. Сохранение схемы в базе данных осуществляется посредством вызова метода <TT>create_all()</tt> в экземпляре метаданных с движком, в котором он должен создавать эти таблицы. По умолчанию create_all не будет пытаться воссоздать таблицы, которые уже существуют в базе данных, и его можно запускать несколько раз. Движок (механизм) SQLAlchemy определен нами ранее в примере 0-1, экземпляр метаданных создан ранее в примере 1-1. Теперь осуществим вызов метода <TT>create_all()</tt>

In [18]:
metadata.create_all(engine)

## Дополнительно: DB Browser for SQLite
https://sqlitebrowser.org/

### Самостоятельная работа

1. Используя библиотеку SQLAlchemy и Юпитер Ноутбук создать реляционную базу данных (до 5-6 таблиц), отражающих финансово-экономческую деятельность отдела предприятия или решающих какую-либо задачу в рамках работы отдела или предпрития.
2. Создать схему (нарисовать).
3. Написать аннтоцию, кратко о смысле деятельности, отраженной в структуре данных.
4. Схему в pdf, png, jpeg и т. д. приложить к письму с результатом.

<p style="color:white">
Результат в формате Юпитер Ноутбук прислать на почту mvsmirnov@fa.ru. В теме письма указать подгруппу, Фимилию, ИО. В отдельной ячейке ноутбука  указать подгруппу, Фимилию, ИО.</p>

<a id=T_5_2></a>
# 5.2. Вставка данных
[<= ](#T_5_1)||[ К оглавлению ](#Ref)||[ =>](#T_5_3)

Теперь, когда в нашей базе данных есть таблицы, приступим к работе с данными внутри этих таблиц. Мы узнаем, как вставлять, извлекать и удалять данные, а затем научимся сортировать, группировать и использовать связи в наших данных. Мы будем использовать язык _SQLExpression Language (SEL),_ называемый также _SQLAlchemy Core_. Начнем с изучения того, как вставлять данные.

## Вставка данных

Вставим первую строку `ListingsAmsterdam.csv`.

In [19]:
am=pd.read_csv('../Data/ListingsAmsterdam.csv',sep=';')
am.head(5)

id                         listing_url  \
0  20168  https://www.airbnb.com/rooms/20168   
1  27886  https://www.airbnb.com/rooms/27886   
2  28871  https://www.airbnb.com/rooms/28871   
3  29051  https://www.airbnb.com/rooms/29051   
4  31080  https://www.airbnb.com/rooms/31080   

                                                name  host_id  host_name  \
0       Studio with private bathroom in the centre 1    59484  Alexander   
1  Romantic, stylish B&B houseboat in canal district    97647       Flip   
2                            Comfortable double room   124245      Edwin   
3                            Comfortable single room   124245      Edwin   
4                2-story apartment + rooftop terrace   133488     Nienke   

  host_is_superhost neighbourhood_cleansed              property_type  \
0                 f           Centrum-Oost  Private room in townhouse   
1                 t           Centrum-West  Private room in houseboat   
2                 t           Centrum-Oost  Private room in apartment   
3                 t           Centrum-Oost  Private room in apartment   
4                 f                   Zuid           Entire apartment   

         room_type  bathrooms_text  ...  first_review  last_review  \
0     Private room  1 private bath  ...    2010-03-02   2020-04-09   
1     Private room       1.5 baths  ...    2012-01-09   2020-07-25   
2     Private room   1 shared bath  ...    2010-08-22   2020-09-20   
3     Private room   1 shared bath  ...    2011-03-16   2020-08-28   
4  Entire home/apt          1 bath  ...    2011-08-06   2017-10-16   

  review_scores_rating  review_scores_accuracy  review_scores_cleanliness  \
0                   89                    10.0                       10.0   
1                   99                    10.0                       10.0   
2                   97                    10.0                       10.0   
3                   95                    10.0                       10.0   
4                   95                     9.0                       10.0   

  review_scores_checkin review_scores_communication  review_scores_location  \
0                  10.0                        10.0                    10.0   
1                  10.0                        10.0                    10.0   
2                  10.0                        10.0                    10.0   
3                  10.0                        10.0                    10.0   
4                  10.0                        10.0                     9.0   

   review_scores_value  reviews_per_month  
0                  9.0               2.58  
1                 10.0               2.01  
2                 10.0               2.68  
3                  9.0               4.05  
4                  9.0               0.28  

[5 rows x 25 columns]

In [20]:
# Все имеющиеся в Амстердаме районы
am_neighs = set(am['neighbourhood_cleansed'])
print(len(am_neighs), am_neighs)

20 {'Watergraafsmeer', 'Geuzenveld - Slotermeer', 'Oud-Noord', 'Noord-Oost', 'Bos en Lommer', 'Zuid', 'Buitenveldert - Zuidas', 'Slotervaart', 'Osdorp', 'Westerpark', 'De Pijp - Rivierenbuurt', 'Centrum-West', 'Noord-West', 'Oostelijk Havengebied - Indische Buurt', 'IJburg - Zeeburgereiland', 'Centrum-Oost', 'Bijlmer-Centrum', 'De Baarsjes - Oud-West', 'Oud-Oost', 'De Aker - Nieuw Sloten'}


In [21]:
# Все имеющиеся в Амстердаме типы собственности
am_prop_types = set(am['property_type'])
print(len(am_prop_types), am_prop_types)

48 {'Entire place', 'Room in hotel', 'Room in hostel', 'Shared room in apartment', 'Entire guest suite', 'Tiny house', 'Private room in house', 'Private room in cabin', 'Entire house', 'Entire guesthouse', 'Entire apartment', 'Private room in villa', 'Private room in loft', 'Entire serviced apartment', 'Entire villa', 'Houseboat', 'Private room in townhouse', 'Private room', 'Entire bed and breakfast', 'Entire townhouse', 'Entire loft', 'Private room in bungalow', 'Room in aparthotel', 'Shared room in house', 'Entire floor', 'Private room in condominium', 'Room in serviced apartment', 'Entire condominium', 'Shared room in hostel', 'Shared room in houseboat', 'Boat', 'Private room in hostel', 'Private room in houseboat', 'Entire cottage', 'Private room in serviced apartment', 'Private room in guesthouse', 'Private room in island', 'Room in bed and breakfast', 'Private room in apartment', 'Shared room in bed and breakfast', 'Entire bungalow', 'Private room in boat', 'Room in boutique hot

In [22]:
# Все имеющиеся в Амстердаме типы комнат
am_room_types = set(am['room_type'])
print(len(am_room_types), am_room_types)

4 {'Hotel room', 'Shared room', 'Entire home/apt', 'Private room'}


In [23]:
am.loc[0] # Пример одной записи набора данных

id                                                                         20168
listing_url                                   https://www.airbnb.com/rooms/20168
name                                Studio with private bathroom in the centre 1
host_id                                                                    59484
host_name                                                              Alexander
host_is_superhost                                                              f
neighbourhood_cleansed                                              Centrum-Oost
property_type                                          Private room in townhouse
room_type                                                           Private room
bathrooms_text                                                    1 private bath
bedrooms                                                                     1.0
beds                                                                         1.0
amenities                   

Создадим оператор вставки, чтобы поместить объект размещения в таблицу. Для этого мы можем вызвать метод `insert()` для таблицы `listing`, а затем использовать оператор `values()` с аргументами для каждого столбца.

In [24]:
# 2-1 Одиночная вставка как метод

ins=listing.insert().values(
    listing_id=int(am.loc[0,'id']),
    listing_name='Studio with private bathroom in the centre 1',
    listing_url='https://www.airbnb.com/rooms/20168',
    host_id=59484,
    neighbourhood_id=4,
    property_type_id=35,
    room_type_id=3,
    amenities=am.loc[0,'amenities'][:300],
    bedrooms=1,
    beds=1,
    price=236
)

print(str(ins))

INSERT INTO listing (listing_id, listing_name, listing_url, host_id, neighbourhood_id, amenities, property_type_id, room_type_id, bedrooms, beds, price) VALUES (:listing_id, :listing_name, :listing_url, :host_id, :neighbourhood_id, :amenities, :property_type_id, :room_type_id, :bedrooms, :beds, :price)


`print(str(ins))` показывает нам фактический оператор SQL, который будет выполнен. Наши  значения были заменены на: `column_name` в этом операторе SQL, именно так SQLAlchemy представляет параметры, отображаемые с помощью функции `str()`. Параметры используются, чтобы гарантировать, что наши данные были правильно экранированы, что снижает проблемы безопасности, такие как атаки с использованием SQL-инъекций. По-прежнему можно получить параметры, посмотрев на скомпилированную версию оператора вставки, потому что каждая внутренняя часть базы данных может обрабатывать параметры по-разному (это контролируется диалектом). 

Метод `compile()` для объекта `ins` возвращает объект `SQLCompiler`, который дает нам доступ к фактическим параметрам, которые будут отправлены с запросом через атрибут params:

In [25]:
ins.compile().params

{'listing_id': 20168,
 'listing_name': 'Studio with private bathroom in the centre 1',
 'listing_url': 'https://www.airbnb.com/rooms/20168',
 'host_id': 59484,
 'neighbourhood_id': 4,
 'amenities': '["Wifi", "Hot water", "Hangers", "Host greets you", "Long term stays allowed", "Carbon monoxide alarm", "Fire extinguisher", "Dedicated workspace", "Paid parking off premises", "Essentials", "Bed linens", "Hair dryer", "TV", "Heating", "Refrigerator", "Free street parking", "Smoke alarm"]',
 'property_type_id': 35,
 'room_type_id': 3,
 'bedrooms': 1,
 'beds': 1,
 'price': 236}

Теперь, когда у нас есть полное представление об операторе вставки и мы понимаем, что будет вставлено в таблицу, мы можем использовать метод `execute()`, чтобы отправить оператор в базу данных, которая вставит запись в таблицу.

In [26]:
connection=engine.connect()

In [27]:
result=connection.execute(ins)

Мы также можем получить идентификатор вставленной записи, обратившись к атрибуту `inserted_primary_key`.

In [28]:
result.inserted_primary_key

(20168,)

Обратите внимание, что значения `beds` и `bedrooms` в таблице `am` веществнного типа, в то время, как в базе данных эти поля целочисленного типа. В данном случае все работает корректно, так как параметрам `bedrooms` и`beds` значения присваиваются в явном виде, но если их получать из столбцов `bedrooms` и `beds` таблицы `df`, то в таблице `df` потребуется преобразование типов, его можно выполнить (с предварительной очисткой данных) так:

`
df['bedrooms']=df['bedrooms'].fillna(0)
df['bedrooms']=pd.to_numeric(df['bedrooms'], downcast='integer')
df['beds']=df['beds'].fillna(0)
df['beds']=pd.to_numeric(df['beds'], downcast='integer')`

Метод `execute()` использует оператор `insert` и другие параметры для компиляции SQL-выражения с помощью компилятора соответствующего диалекта базы данных. Этот компилятор строит нормальное параметризованное выражение и возвращается в метод `execute`, который отправляет оператор SQL в базу данных через соответствующее соединение. Затем сервер базы данных выполняет оператор и возвращает результат операции.

<img src=../Img/Execute_method.png alt="Execute method" width="390">

В дополнение к вставке в качестве метода экземпляра объекта `Table`, `insert` также доступен как функция верхнего уровня для случаев, когда таблица изначально неизвестна. Например, компания airbnb дополнительно к объектам в Амстердаме может иметь еще одну таблицу для Лиона (Франция): `listing_lyon`. Использование функции вставки позволяет использовать один оператор и подменять таблицы.

`ins=insert(listing).values(
    listing_id=20168,
    listing_name='Studio with private bathroom in the centre 1',
    listing_url='https://www.airbnb.com/rooms/20168',
    host_id=59484,
    neighbourhood_id=1,
    property_type_id=1,
    room_type_id=1,
    amenities=df.loc[0,'amenities'],
    bedrooms=1,
    beds=1,
    price=236
)`

In [29]:
lyon=pd.read_csv('../Data/ListingsLyon.csv',sep=';')
lyon.head(1)

id                         listing_url  \
0  56766  https://www.airbnb.com/rooms/56766   

                                 name  host_id host_name host_is_superhost  \
0  Amazing duplex-terrace in old Lyon   269557  Isabelle                 f   

  neighbourhood_cleansed     property_type        room_type bathrooms_text  \
0      5e Arrondissement  Entire apartment  Entire home/apt        2 baths   

   ...  first_review  last_review review_scores_rating  \
0  ...    2010-11-15   2018-09-04                   94   

   review_scores_accuracy  review_scores_cleanliness review_scores_checkin  \
0                     9.0                        9.0                  10.0   

  review_scores_communication  review_scores_location  review_scores_value  \
0                        10.0                    10.0                  9.0   

   reviews_per_month  
0               0.45  

[1 rows x 25 columns]

In [30]:
lyon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5089 entries, 0 to 5088
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   id                           5089 non-null   int64  
 1   listing_url                  5089 non-null   object 
 2   name                         5087 non-null   object 
 3   host_id                      5089 non-null   int64  
 4   host_name                    5089 non-null   object 
 5   host_is_superhost            5089 non-null   object 
 6   neighbourhood_cleansed       5089 non-null   object 
 7   property_type                5089 non-null   object 
 8   room_type                    5089 non-null   object 
 9   bathrooms_text               5088 non-null   object 
 10  bedrooms                     4409 non-null   float64
 11  beds                         5078 non-null   float64
 12  amenities                    5089 non-null   object 
 13  price             

In [31]:
lyon.loc[0]

id                                                                         56766
listing_url                                   https://www.airbnb.com/rooms/56766
name                                          Amazing duplex-terrace in old Lyon
host_id                                                                   269557
host_name                                                               Isabelle
host_is_superhost                                                              f
neighbourhood_cleansed                                         5e Arrondissement
property_type                                                   Entire apartment
room_type                                                        Entire home/apt
bathrooms_text                                                           2 baths
bedrooms                                                                     3.0
beds                                                                         4.0
amenities                   

In [32]:
# Все имеющиеся в Лионе районы
lyon_neighs = set(lyon['neighbourhood_cleansed'])
print(len(lyon_neighs), lyon_neighs)

9 {'2e Arrondissement', '7e Arrondissement', '9e Arrondissement', '6e Arrondissement', '3e Arrondissement', '8e Arrondissement', '4e Arrondissement', '1er Arrondissement', '5e Arrondissement'}


In [33]:
# Все имеющиеся в Лионе типы собственности
lyon_prop_types = set(lyon['property_type'])
print(len(lyon_prop_types), lyon_prop_types)

37 {'Entire place', 'Room in hotel', 'Room in hostel', 'Shared room in apartment', 'Entire guest suite', 'Tiny house', 'Private room in house', 'Entire house', 'Entire guesthouse', 'Entire apartment', 'Private room in villa', 'Private room in loft', 'Private room in cottage', 'Entire villa', 'Entire serviced apartment', 'Houseboat', 'Private room in townhouse', 'Private room', 'Shared room in loft', 'Entire townhouse', 'Entire loft', 'Room in aparthotel', 'Private room in condominium', 'Shared room in condominium', 'Room in serviced apartment', 'Entire condominium', 'Shared room in hostel', 'Private room in hostel', 'Private room in houseboat', 'Private room in serviced apartment', 'Private room in guesthouse', 'Room in bed and breakfast', 'Private room in apartment', 'Private room in boat', 'Room in boutique hotel', 'Private room in guest suite', 'Private room in bed and breakfast'}


In [34]:
# Все имеющиеся в Лионе типы комнат
lyon_room_types = set(lyon['room_type'])
print(len(lyon_room_types), lyon_room_types)

4 {'Hotel room', 'Shared room', 'Entire home/apt', 'Private room'}


In [35]:
listing_lyon=Table('listing_lyon',metadata,
                   Column('listing_id',Integer(),primary_key=True),
                   Column('listing_name',String(50),index=True),
                   Column('listing_url',String(255)),
                   Column('host_id',Integer()),
                   Column('neighbourhood_id',Integer()),
                   Column('amenities',String(300)),
                   Column('property_type_id',Integer()),
                   Column('room_type_id',Integer()),
                   Column('bedrooms',Integer()),
                   Column('beds',Integer()),
                   Column('price',Numeric(7,2)),
                   CheckConstraint('price >= 0.00', name='lyon_price_positive'),
                   extend_existing=True
                  )

In [36]:
metadata.create_all(engine)

In [37]:
#2-3. Функция insert

ins=insert(listing_lyon).values(
    listing_id=int(lyon.loc[0,'id']),
    listing_name=lyon.loc[0,'name'],
    listing_url=lyon.loc[0,'listing_url'],
    host_id=int(lyon.loc[0,'host_id']),
    neighbourhood_id=5,
    amenities=lyon.loc[0,'amenities'][:300],
    property_type_id=1,
    room_type_id=1,
    bedrooms=int(lyon.loc[0,'bedrooms']),
    beds=int(lyon.loc[0,'beds']),
    price=lyon.loc[0,'price']
)

print(str(ins))
print(ins.compile().params)

INSERT INTO listing_lyon (listing_id, listing_name, listing_url, host_id, neighbourhood_id, amenities, property_type_id, room_type_id, bedrooms, beds, price) VALUES (:listing_id, :listing_name, :listing_url, :host_id, :neighbourhood_id, :amenities, :property_type_id, :room_type_id, :bedrooms, :beds, :price)
{'listing_id': 56766, 'listing_name': 'Amazing duplex-terrace in old Lyon', 'listing_url': 'https://www.airbnb.com/rooms/56766', 'host_id': 269557, 'neighbourhood_id': 5, 'amenities': '["Shampoo", "Long term stays allowed", "Kitchen", "TV", "Crib", "Dedicated workspace", "Host greets you", "Dryer", "Paid parking off premises", "Wifi", "Carbon monoxide alarm", "Pack \\u2019n Play/travel crib", "Essentials", "Hair dryer", "Iron", "Luggage dropoff allowed", "Smoke alarm", "Washer", "H', 'property_type_id': 1, 'room_type_id': 1, 'bedrooms': 3, 'beds': 4, 'price': 250.0}


In [38]:
result=connection.execute(ins)
result.inserted_primary_key

(56766,)

Метод `execute` объекта `connection` может принимать значения в качестве именованных аргументов, которые передаются после выражения. Когда выражение компилируется, он добавляет названия именованных аргументов в список столбцов, а каждое из их значений в часть ЗНАЧЕНИЯ оператора SQL.

In [39]:
# район, тип собственности, тип комнаты для вставляемой записи
print(am.loc[1,'id'])
print(am.loc[1,'neighbourhood_cleansed'])
print(am.loc[1,'property_type'])
print(am.loc[1,'room_type'])

27886
Centrum-West
Private room in houseboat
Private room


In [40]:
# 2-4

ins = listing.insert()

result = connection.execute(
    ins,
    listing_id=int(am.loc[1,'id']),
    listing_name=am.loc[1,'name'],
    listing_url=am.loc[1,'listing_url'],
    host_id=int(am.loc[1,'host_id']),
    neighbourhood_id=5,
    amenities=am.loc[1,'amenities'][:300],
    property_type_id=30,
    room_type_id=3,
    bedrooms=int(am.loc[1,'bedrooms']),
    beds=int(am.loc[1,'beds']),
    price=am.loc[1,'price']
)
result.inserted_primary_key

(27886,)

Хотя такой способ не часто используется на практике для одиночных вставок, он дает иллюстрацию компиляции и сборки оператора перед отправкой на сервер базы данных. 

Мы можем вставить сразу несколько записей, используя список словарей с данными. Воспользуемся этим, чтобы вставить еще две записи в таблицу _listing_ (Пример 2-5).

In [41]:
# 2-5

listing_list=[
    {
        'listing_id' : int(am.loc[2,'id']),
        'listing_name' : am.loc[2,'name'],
        'listing_url' : am.loc[2,'listing_url'],
        'host_id' : int(am.loc[2,'host_id']),
        'neighbourhood_id' : 4,
        'amenities' : am.loc[2,'amenities'][:300],
        'property_type_am' : 19,
        'room_type_id' : 3,
        'bedrooms' : int(am.loc[2,'bedrooms']),
        'beds' : int(am.loc[2,'beds']),
        'price' : am.loc[2,'price']
    },
    {
        'listing_id' : int(am.loc[3,'id']),
        'listing_name' : am.loc[3,'name'],
        'listing_url' : am.loc[3,'listing_url'],
        'host_id' : int(am.loc[3,'host_id']),
        'neighbourhood_id' : 4,
        'amenities' : am.loc[3,'amenities'][:100],
        'property_type_am' : 19,
        'room_type_id' : 3,
        'bedrooms' : int(am.loc[3,'bedrooms']),
        'beds' : int(am.loc[3,'beds']),
        'price' : am.loc[3,'price']
    }
]

In [42]:
result=connection.execute(ins,listing_list)

Добавим еще одну запись, выполнив вставку из кортежа.

In [43]:
record=(int(am.loc[4,'id']), am.loc[4,'name'], am.loc[4,'listing_url'], 
            int(am.loc[4,'host_id']), 20, am.loc[4,'amenities'][:100], 
            2, 1, int(am.loc[4,'bedrooms']), int(am.loc[4,'beds']), am.loc[4,'price'])
ins = insert(listing).values(record)
connection.execute(ins)

Словари в списке должны иметь одинаковые ключи. SQLAlchemy компилирует выражение с первым словарем в списке и завершится ошибкой, если последующие словари будут другими. Наполним еще насколько таблиц базы данных _listings_.

In [44]:
def insert_values(table, values_list):
    for value in values_list:
        ins = insert(table).values(value)
        connection.execute(ins)

In [45]:
neigh_list=[]
for k, item in enumerate(am_neighs):
    neigh_list.append((k+1, item))
insert_values(neighbourhood, neigh_list)

In [46]:
room_list=[]
for k, item in enumerate(am_room_types):
    room_list.append((k+1, item))
insert_values(room_type, room_list)

In [47]:
prop_list=[]
for k, item in enumerate(am_prop_types):
    prop_list.append((k+1, item))
insert_values(property_type, prop_list)

In [48]:
# Если в таблице user уже есть какие-либо данные, удалим их
#d=delete(user)
#print(str(d))
#print(d.compile().params)
#r=connection.execute(d)
#print(r.rowcount)

In [49]:
user_list=[(1,'Nicolas','nicolas@rambler.ru','+7-929-616-88-77','@#$%890'),
           (2,'Lida','lidaok@gmail.com','+7-929-616-88-77','yyT$%333'),
           (3,'Vera','lveramuns@gmail.com','+7-353-214-12-90','yyT$%333'),
           (4,'Ivan','ivaturgenev@yandex.ru','+7-047-121-89-95','tT6^7&#20Oy'),
           (5,'Svetlana','svetaivanova@microsoft.com','+7-812-555-48-71','SD%@OUsdc7')
          ]
insert_values(user,user_list)

In [50]:
order_list=[(1,1,True,500),
            (2,2,True,150),
            (3,3,True,180),
            (4,1,True,200),
            (5,2,True,220)]
insert_values(order,order_list)

In [51]:
line_list=[(1,1,20168,datetime.strptime('2020-05-07','%Y-%m-%d'), datetime.strptime('2020-05-17','%Y-%m-%d')),
           (2,1,27886,datetime.strptime('2020-05-17','%Y-%m-%d'), datetime.strptime('2020-05-27','%Y-%m-%d')),
           (3,2,28871,datetime.strptime('2020-08-01','%Y-%m-%d'), datetime.strptime('2020-08-10','%Y-%m-%d')),
           (4,3,29051,datetime.strptime('2020-05-07','%Y-%m-%d'), datetime.strptime('2020-05-17','%Y-%m-%d'))
          ]
insert_values(line_item,line_list)

In [52]:
host_list=[(59484,'Alexander'),(97647,'Flip'),(124245,'Edwin'),(133488,'Nienke')]
insert_values(host,host_list)

### Самостоятельная работа

1. Используя библиотеку SQLAlchemy и Юпитер Ноутбук наполнить созданную в результате выполнения предыдущего домашнего задания реляционную базу данных записями, содержащими сведения о финансово-экономческой деятельности отдела, предприятия или решающих какую-либо задачу в рамках работы отдела или предпрития.
2. В процессе наполнения структуры данными для разных таблиц использовать обе изученные техники:<br>
а) одиночную вставку;<br>
б) множественную вставку из словаря.
<p style="color:white">
Результат в формате Юпитер Ноутбук прислать на почту mvsmirnov@fa.ru. В теме письма указать подгруппу, Фимилию, ИО. В отдельной ячейке ноутбука  указать подгруппу, Фимилию, ИО.
</p>

<a id=T_5_3></a>
# 5.3. Запросы к данным
[<= ](#T_5_2)||[ К оглавлению ](#Ref)||[ =>](#T_5_4)

Построение запроса начнем с использования функции *select()*, которая аналогична стандартному оператору `SQL SELECT`. Если данное занятие начинается в новой сессии Юпитер ноутбук, импортируем необходимые модули и библиотеки.

In [53]:
from sqlalchemy import (select, create_engine, MetaData, Table, Numeric, String, 
                        insert, update, delete, cast)
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

Создадим механизм и подключимся к ранее созданной базе данных _listings.db_

In [54]:
engine=create_engine('sqlite:///listings.db')
metadata=MetaData()
connection=engine.connect()

Создадим объект *listing* и другие объекты, связанные с таблицами базы данных *listings.db.*

In [55]:
listing=Table('listing', metadata, autoload=True, autoload_with=engine)
neighbourhood=Table('neighbourhood', metadata, autoload=True, autoload_with=engine)
host=Table('host', metadata, autoload=True, autoload_with=engine)
line_item=Table('line_item', metadata, autoload=True, autoload_with=engine)
order=Table('order', metadata, autoload=True, autoload_with=engine)
property_type=Table('property_type', metadata, autoload=True, autoload_with=engine)
room_type=Table('room_type', metadata, autoload=True, autoload_with=engine)
user=Table('user', metadata, autoload=True, autoload_with=engine)

Отберем все записи таблицы _'listing'_. Для этого передадим объект _listing_ в функцию _select._

In [56]:
# 3-1

s = select([listing])
rp = connection.execute(s)
results = rp.fetchall()
results

[(20168, 'Studio with private bathroom in the centre 1', 'https://www.airbnb.com/rooms/20168', 59484, 4, '["Wifi", "Hot water", "Hangers", "Host greets you", "Long term stays allowed", "Carbon monoxide alarm", "Fire extinguisher", "Dedicated workspace", "Paid parking off premises", "Essentials", "Bed linens", "Hair dryer", "TV", "Heating", "Refrigerator", "Free street parking", "Smoke alarm"]', 35, 3, 1, 1, Decimal('236.00')),
 (27886, 'Romantic, stylish B&B houseboat in canal district', 'https://www.airbnb.com/rooms/27886', 97647, 5, '["Carbon monoxide alarm", "Private living room", "Refrigerator", "Dishes and silverware", "Smoke alarm", "Patio or balcony", "Private entrance", "TV" ... (2 characters truncated) ... "Wifi", "Smart lock", "Hot water", "Coffee maker", "Hangers", "Fire extinguisher", "Shampoo", "Luggage dropoff allowed", "Lake access", "Long term st', 30, 3, 1, 1, Decimal('135.00')),
 (28871, 'Comfortable double room', 'https://www.airbnb.com/rooms/28871', 124245, 4, '["Wi

Переменная _result_ содержит список всех записей таблицы _listing._ В примере 3-1 в функцию _select()_ передан список из одной таблицы. Как правило, _select()_ ожидает получить список столбцов, но если передается имя таблицы, то запрос осуществляется по всем столбцам. Выполним `str(s)`, чтобы увидеть формулу запроса.

In [57]:
str(s)

'SELECT listing.listing_id, listing.listing_name, listing.listing_url, listing.host_id, listing.neighbourhood_id, listing.amenities, listing.property_type_id, listing.room_type_id, listing.bedrooms, listing.beds, listing.price \nFROM listing'

_select_ можно использовать как метод объекта _listing._

In [58]:
s=listing.select()
rp=connection.execute(s)
rp.fetchone()

(20168, 'Studio with private bathroom in the centre 1', 'https://www.airbnb.com/rooms/20168', 59484, 4, '["Wifi", "Hot water", "Hangers", "Host greets you", "Long term stays allowed", "Carbon monoxide alarm", "Fire extinguisher", "Dedicated workspace", "Paid parking off premises", "Essentials", "Bed linens", "Hair dryer", "TV", "Heating", "Refrigerator", "Free street parking", "Smoke alarm"]', 35, 3, 1, 1, Decimal('236.00'))

В примере 3-1 используется объект _ResultProxy,_ созданный в результате вызова исполняемого метода соединения. Этот объект предоставляет доступ к данным по индексу, имени столбца или объекту столбца.  Пример 3-2 демонстрирует все три способа.

In [59]:
# 3-2

first_row=results[0] # Первая запись
print(first_row[1]) # Доступ к значению по индексу
print(first_row.listing_name) # Доступ к значению по имени соответствующего столбца
print(first_row[listing.c.listing_name]) # Доступ по имени объекта столбца

Studio with private bathroom in the centre 1
Studio with private bathroom in the centre 1
Studio with private bathroom in the centre 1


Мы также можем использовать _ResultProxy_ для доступа к данным в цикле. Например,  напечатать имя каждого объекта размещения (пример 3-3).

In [60]:
# 3-3

rp=connection.execute(s)
for record in rp:
    print(record.listing_name)

Studio with private bathroom in the centre 1
Romantic, stylish B&B houseboat in canal district
Comfortable double room
Comfortable single room
2-story apartment + rooftop terrace


Другими методами _ResultProxy_ являются:

- `first()` - возвращает первую запись, если она есть, и закрывает соединение
- `fetchone()` - возвращает строку и оставляет соединение открытым для дополнительных запросов
- `scalar()` - возвращает единственное значение, если результатом является один столбец единственной записи
- `keys()` - возвращает список названий столбцов результата запроса

Также приведем здесь полезные атрибуты
- `inserted_primary_key` - возвращает значение первичного ключа добавленной записи
- `rowcount` - возвращает число обновленных или удаленных записей

Советы по созданию хорошего кода

- Используйте метод `first` для получения одной записи вместо методов `fetchone` и `scalar`, потому что он более понятен коллегам-кодировщикам.
- Используйте итеративную версию _ResultProxy_ вместо методов `fetchall` и `fetchone`. Это более эффективно с точки зрения использования памяти.
- Будьте внимательны при использовании метода `fetchone`, поскольку он оставляет соединения открытыми. 
- Используйте метод `scalar` экономно, поскольку он вызывает ошибки, если запрос  возвращает более одной строки с одним столбцом.

## Управление столбцами запроса

В предыдущих примерах в каждом запросе мы получали все столбцы каждой записи. Часто нам нужны только некоторые из столбцов. Для сокращения числа столбцов конкретные столбцы указываются списком и передаются в функцию `select`.

In [61]:
# 3-4

s = select([listing.c.listing_name, listing.c.host_id])
rp = connection.execute(s)
result=rp.first()
result

('Studio with private bathroom in the centre 1', 59484)

## Упорядочивание  результатов запроса

Чтобы упорядочить результаты запроса используем `order_by()`

In [62]:
# 3-5

s=select([listing.c.listing_name, listing.c.host_id])
s=s.order_by(listing.c.listing_name)
rp=connection.execute(s)
for rec in rp:
    print(f'{rec.host_id} \t|  {rec.listing_name}')

133488 	|  2-story apartment + rooftop terrace
124245 	|  Comfortable double room
124245 	|  Comfortable single room
97647 	|  Romantic, stylish B&B houseboat in canal district
59484 	|  Studio with private bathroom in the centre 1


В предыдущем примере использован общепринятый подход постепенного наращивания условий запроса: сначала создан запрос _s_, затем к нему добавлено условие упорядочивания. Такой подход повышает читаемость кода и обладает дополнительными преимуществами, такими, как возможность формировать выражения запроса по условию.

Подобные запросы можно написать и в одну строку:
```
connection.execute(select([listing.c.listing_name,
    listing.c.host_id]).order_by(listing.c.listing_name)).fetchall()
```
Однако "длинных" конструкций в одну строку следует избегать для предотвращения ошибок.

Для упорядочивания по убыванию используем функцию `desc()`

In [63]:
# 3-6

from sqlalchemy import desc

s = select([listing.c.listing_name, listing.c.host_id])
s = s.order_by(desc(listing.c.listing_name))
rp = connection.execute(s)
for rec in rp:
    print(f'{rec.host_id} \t|  {rec.listing_name}')

59484 	|  Studio with private bathroom in the centre 1
97647 	|  Romantic, stylish B&B houseboat in canal district
124245 	|  Comfortable single room
124245 	|  Comfortable double room
133488 	|  2-story apartment + rooftop terrace


Существует также и метод `.desc()`, тогда напишем `listing.c.listing_name.desc()`

## Ограничение числа записей

В предыдущих примерах мы использовали методы `first()` или `fetchone()`, чтобы вернуть только одну строку. И хотя _ResultProxy_ предоставил нам одну строку, фактически запрос "пробежал" по всем строкам и получил доступ ко всем результатам, а не только к отдельной записи. Если мы хотим ограничить запрос, мы можем использовать функцию `limit()`. Например предположим, что мы рассматриваем только дорогие размещения и хотим знать, какие три размещения самые дорогие. Тогда используем упорядоченный запрос и добавим `limit()` для возврата трех самых дорогих объектов размещения.

In [64]:
# 3-7

s=select([listing.c.listing_name, listing.c.price])
s=s.order_by(desc(listing.c.price))
s=s.limit(3)
rp=connection.execute(s)
result=rp.fetchall()
result

[('Studio with private bathroom in the centre 1', Decimal('236.00')),
 ('2-story apartment + rooftop terrace', Decimal('219.00')),
 ('Romantic, stylish B&B houseboat in canal district', Decimal('135.00'))]

Для приведения цены объекта размещения к целочисленному типу используем функцию `int()`. В следующем примере использован генератор списков.

In [65]:
# 3-8

s=select([listing.c.listing_name, listing.c.price])
s=s.order_by(desc(listing.c.price))
s=s.limit(3)
rp=connection.execute(s)

print([int(row.price) for row in rp])

[236, 219, 135]


## Встроенные функции
SQLAlchemy может использовать функции SQL, находящиеся в серверной базе данных. Две часто используемые функции базы данных - это SUM() и COUNT(). Чтобы использовать их, нужно импортировать модуль _sqlalchemy.sql.func._ Эти функции применяются к столбцам, как показано в примере 3-9. Обратите внимание на метод _.scalar(),_ который возвращает значение крайнего левого столбца первой записи. Импорт модуля _func_ всегда рекоменжуется делать, чтобы не было конфликта со встроенной в языке Пайтон функцией _sum()_.

In [66]:
# 3-9

from sqlalchemy.sql import func
s = select([func.sum(listing.c.bedrooms)])
rp = connection.execute(s)
print(rp.scalar())

7


Теперь используем функцию _count(),_ чтобы узнать, сколько у нас районов.

In [67]:
# 3-10

s=select([func.count(neighbourhood.c.neighbourhood_id)])
rp=connection.execute(s)
record=rp.first()
print(record.keys())
print(record.count_1)

RMKeyView(['count_1'])
20


Имя столбца присваивается автоматически в формате  _func_name_position_. Можно использовать функцию _label()_ для присвоения имен столбцам.

In [68]:
# 3-11

s=select([func.count(neighbourhood.c.neighbourhood_id).label('Число_районов')])
rp=connection.execute(s)
record=rp.first()
print(record.keys())
print(record.Число_районов)

RMKeyView(['Число_районов'])
20


## Фильтрация

Фильтрация производится посредством добавления выражения _where()._ Можно указывать несколько _where()_ последовательно в одном запросе, тогда они работают как операторы _AND._

In [69]:
# 3-12

s=select([listing.c.listing_url, listing.c.listing_id]).where(listing.c.listing_id>29000)
rp=connection.execute(s)
rec=rp.first()
print(rec.items())

[('listing_url', 'https://www.airbnb.com/rooms/29051'), ('listing_id', 29051)]


Мы можем использовать выражение _where()_ для поиска названий, содержащих подстроку. Найдем все размещения, содержащие подсроку "room".

In [70]:
# 3-13

s=select([listing.c.listing_name])
s=s.where(listing.c.listing_name.like('%room%'))
rp=connection.execute(s)
rec=rp.fetchall()
print(rec)

[('Comfortable double room',), ('Comfortable single room',), ('Studio with private bathroom in the centre 1',)]


## Условные методы
Условные методы аналогичны стандартной конструкции оператора SQL.

In [71]:
pd.DataFrame(
    [
    ["between(cleft,cright)", "Поиск значения между cleft и cright"],
    ["concat(column_two)", "Соединяет столбкц со столбцом 2"],
    ["distinct()", "Вывод без повторов"],
    ["in_([list])", "Если значение находится в списке"],
    ["is_(None)", "Проверка на пустое значение"],
    ["contains(string)", "Если значение содержит подстроку (регистр)"],
    ["endswith(string)", "Оканчивается на подстроку"],
    ["like(string)", "Поиск по шаблону (зависит от регистра)"],
    ["startswith(string)", "Начинается с"],
    ["ilike(string)","Поиск по шаблону (не зависит от регистра)"],
    ["notlike, notin_ ...", "имеются инверсии not<method>"],
    ["isnot","Единственное исключение"]
    ], 
    columns=['Метод','Описание']
)

Метод                                    Описание
0   between(cleft,cright)         Поиск значения между cleft и cright
1      concat(column_two)             Соединяет столбкц со столбцом 2
2              distinct()                          Вывод без повторов
3             in_([list])            Если значение находится в списке
4               is_(None)                 Проверка на пустое значение
5        contains(string)  Если значение содержит подстроку (регистр)
6        endswith(string)                   Оканчивается на подстроку
7            like(string)      Поиск по шаблону (зависит от регистра)
8      startswith(string)                                Начинается с
9           ilike(string)   Поиск по шаблону (не зависит от регистра)
10    notlike, notin_ ...                имеются инверсии not<method>
11                  isnot                     Единственное исключение

## Операторы

Можно использовать операторы сравнения и бинарные:<br>
- ==, <, >, <=, >=
- \, +, -, *, /, %

SQLAlchemy обеспечивает перегрузку для большинства стандартных операторов Python. Сюда входят все стандартные операторы сравнения (==,! =, <,>, <=,> =), которые действуют точно так же, как операторы Python. Оператор == получает дополнительную перегрузку при сравнении с None, которая преобразует его в оператор IS NULL. Арифметические операторы (\ +, -, *, / и %) также поддерживаются с дополнительными возможностями для независимой от базы данных конкатенации строк.

In [72]:
#3-14

s=select([listing.c.listing_name + ' || ' +listing.c.listing_url])
rp=connection.execute(s)
rp.fetchall()

[('Studio with private bathroom in the centre 1 || https://www.airbnb.com/rooms/20168',),
 ('Romantic, stylish B&B houseboat in canal district || https://www.airbnb.com/rooms/27886',),
 ('Comfortable double room || https://www.airbnb.com/rooms/28871',),
 ('Comfortable single room || https://www.airbnb.com/rooms/29051',),
 ('2-story apartment + rooftop terrace || https://www.airbnb.com/rooms/31080',)]

Операторы часто используются для вычисления значений выражений с участием нескольких столбцов. В нижеследующем примере применена функция _cast()_.

In [73]:
# 3-15

from sqlalchemy import cast, String
s=select([listing.c.listing_id, listing.c.price,
          cast((listing.c.price*1.13), Numeric(5,0)).label('mult')])

for row in connection.execute(s):
    print(row.listing_id, row.price, row.mult)

27886 135.00 153
29051 55.00 62
31080 219.00 247
20168 236.00 267
28871 75.00 85


Функцию _cast()_ можно использовать для преобразования типов.

In [74]:
# 3-16

from sqlalchemy import cast, String
s=select([listing.c.price, listing.c.listing_name + ' for ' +
          cast((listing.c.price), String(20)).label('mult') + 
          ' euros'])
rp=connection.execute(s)
for row in rp:
    print(row[1])

Studio with private bathroom in the centre 1 for 236 euros
Romantic, stylish B&B houseboat in canal district for 135 euros
Comfortable double room for 75 euros
Comfortable single room for 55 euros
2-story apartment + rooftop terrace for 219 euros


Булевы операторы

&, |, ~


## Логические связки

and_(), or_(), not_()

In [75]:
# 3-17

from sqlalchemy import and_, or_, not_

s=select([listing.c.listing_name, listing.c.price]).where(
    and_(
        listing.c.price < 200,
        listing.c.price > 100
    )
)
rp=connection.execute(s)
result=rp.fetchall()
result

[('Romantic, stylish B&B houseboat in canal district', Decimal('135.00'))]

In [76]:
# 3-18

s=select([listing.c.listing_name, listing.c.price]).where(
    or_(
        listing.c.price.between(100,200),
        listing.c.listing_name.contains('%omfortable')
    )
)
rp=connection.execute(s)
result=rp.fetchall()
result

[('Romantic, stylish B&B houseboat in canal district', Decimal('135.00')),
 ('Comfortable double room', Decimal('75.00')),
 ('Comfortable single room', Decimal('55.00'))]

## Обновление данных. Метод _update()_

Подобно методу _insert(),_ существует также метод обновления с синтаксисом, почти идентичным вставкам, за исключением того, что он может содержать условие _where,_ указывающее, какие строки следует обновлять. Как и выражения вставки, выражения обновления могут быть созданы либо функцией _update()_, либо методом _update()_.

Предположим, на объекте 28871 произошел ремонт, сменился владелец и теперь необходимо обновить код типа собственности в поле _property_type_id_

In [77]:
# 3-19

u=update(listing).where(listing.c.listing_id==28871)
u=u.values(property_type_id=33)
result=connection.execute(u)

In [78]:
s=select([listing.c.listing_id, listing.c.listing_name, listing.c.property_type_id])
s=s.where(listing.c.listing_id==28871)
result=connection.execute(s).first()
print(result)

(28871, 'Comfortable double room', 33)


## Удаление данных. Метод _delete()_

Чтобы создать оператор удаления, можно использовать либо функцию _delete(),_ либо метод _delete()_. В отличие от _insert()_ и _update(), delete()_ не принимает параметров значений, только необязательное предложение _where,_ при отсутствии которого из таблицы удаляются все строки.

Добавим одну строку заказа. Сначала узнаем максимальное значение первичного ключа в таблице _line_item_.

In [79]:
s=select([func.max(line_item.c.line_item_id)])
max_line=connection.execute(s).scalar()
print(max_line)

4


Теперь добавим запись в таблицу _line_item_. Пусть это будет строка заказа № 5 с целью бронирования объекта 31080 в период с 1 по 17 марта. В качестве значения первичного ключа используем _max_line+1_.

In [80]:
ins=insert(line_item)
ins=ins.values((max_line+1,5,31080,datetime.strptime('2021.03.01','%Y.%m.%d'), 
                datetime.strptime('2020.03.17','%Y.%m.%d')))

print(str(ins))
print(ins.compile().params)

rp=connection.execute(ins)

INSERT INTO line_item (line_item_id, order_id, listing_id, item_start_date, item_end_date) VALUES (:line_item_id, :order_id, :listing_id, :item_start_date, :item_end_date)
{'line_item_id': 5, 'order_id': 5, 'listing_id': 31080, 'item_start_date': datetime.datetime(2021, 3, 1, 0, 0), 'item_end_date': datetime.datetime(2020, 3, 17, 0, 0)}


С помощью атрибута _inserted_primary_key_ убедимся, что соответствующая строка заказа добавлена.

In [81]:
print(rp.inserted_primary_key)

(5,)


Теперь удалим добавленную строку.

In [82]:
# 3-20

d=delete(line_item).where(line_item.c.line_item_id==max_line+1)
print(str(d))
print(d.compile().params)

DELETE FROM line_item WHERE line_item.line_item_id = :line_item_id_1
{'line_item_id_1': 5}


In [83]:
result=connection.execute(d)
result.rowcount

1

## Объединение. Методы _join()_ и _outerjoin()_

Воспользуемся методом _join(),_ чтобы узнать, как запрашивать связанные данные. Например, чтобы выполнить заказ, сделанный пользователем _Lida,_ нам необходимо сделать зарос к таблицам _user, order, line_item_ и _listing_. Для того, чтобы связать эти таблицы в запросе, используем метод _join()_ и предложение _select_from()_.

In [84]:
# 3-21

columns=[user.c.user_name, listing.c.listing_name,
         cast(line_item.c.item_start_date, String(20))
        ]
orders=select(columns)
orders=orders.select_from(order.join(user).join(line_item).join(listing))
orders=orders.where(user.c.user_name=='Lida')

In [85]:
print(str(orders))

SELECT "user".user_name, listing.listing_name, CAST(line_item.item_start_date AS VARCHAR(20)) AS item_start_date 
FROM "order" JOIN "user" ON "user".user_id = "order".user_id JOIN line_item ON "order".order_id = line_item.order_id JOIN listing ON listing.listing_id = line_item.listing_id 
WHERE "user".user_name = :user_name_1


In [86]:
result=connection.execute(orders).fetchall()
for row in result:
    print(row)

('Lida', 'Comfortable double room', '2020-08-01 00:00:00.000000')


В следующем примере запросы объединяются по условию.

In [87]:
# 3-22

def get_orders_by_customer(cust_name, detailes):
    columns=[user.c.user_name, user.c.phone, order.c.order_id]
    joins=user.join(order)
    if detailes:
        columns.extend([listing.c.listing_name, line_item.c.item_price])
        joins=joins.join(line_item).join(listing)        
    cust_orders=select(columns)
    cust_orders=cust_orders.select_from(order.join(user).join(line_item).join(listing))
    cust_orders=cust_orders.where(user.c.user_name==cust_name)
    result=connection.execute(cust_orders).fetchall()
    return result

In [88]:
get_orders_by_customer("Lida", True)

[('Lida', '+7-929-616-88-77', 2, 'Comfortable double room', None)]

## Группировка

In [89]:
s=select([listing])
rp=connection.execute(s)
rp.keys()

RMKeyView(['listing_id', 'listing_name', 'listing_url', 'host_id', 'neighbourhood_id', 'amenities', 'property_type_id', 'room_type_id', 'bedrooms', 'beds', 'price'])

In [90]:
# 3-23

columns=[listing.c.host_id, func.count(listing.c.listing_id)]
all_hosts=select(columns)
all_hosts=all_hosts.group_by(listing.c.host_id)

result=connection.execute(all_hosts).fetchall()
for row in result:
    print(row)

(59484, 1)
(97647, 1)
(124245, 2)
(133488, 1)


## Прямые запросы

In [91]:
# 3-24

result = connection.execute("select * from host").fetchall()
print(result)

[(59484, 'Alexander'), (97647, 'Flip'), (124245, 'Edwin'), (133488, 'Nienke')]


In [92]:
# 3-25

from sqlalchemy import text
stmt = select([host]).where(text("host_name='Alexander'"))
print(connection.execute(stmt).fetchall())

[(59484, 'Alexander')]


<a id=T_5_4></a>

# 5.4. Исключения и транзакции
[<= ](#T_5_3)||[ К оглавлению ](#Ref)||[ =>](#T_5_5)

В предыдущих разделах мы работали с данными с помощью функций и методов и избегали любых действий, которые могли привести к ошибке. На этом занятии мы намеренно выполним некоторые действия неправильно, чтобы увидеть типы ошибок и то, как мы должны на них реагировать. Мы завершим занятие, узнав, как группировать выражения, которые должны быть успешными, в транзакции, чтобы быть уверенным в том, что группа либо выполняется должным образом, либо правильно очищается.

## Исключения
В SQLAlchemy может возникать множество исключений, остановимся на наиболее распространенных: *AttributeErrors* и *IntegrityErrors*. Загрузим созданные ранее таблицы.

In [93]:
from datetime import datetime

from sqlalchemy import (select, create_engine, MetaData, Table, Numeric, String, 
                        insert, update, delete)

metadata = MetaData()

Создадим механизм и подключимся к ранее созданной базе данных _listings.db_

In [94]:
engine=create_engine('sqlite:///listings.db')
metadata=MetaData()
connection=engine.connect()

Создадим объект _listing,_ и другие объекты, связанные с таблицей _'listing'_ и другими таблицами базы данных _listings.db_

In [95]:
listing=Table('listing', metadata, autoload=True, autoload_with=engine)
neighbourhood=Table('neighbourhood', metadata, autoload=True, autoload_with=engine)
host=Table('host', metadata, autoload=True, autoload_with=engine)
line_item=Table('line_item', metadata, autoload=True, autoload_with=engine)
order=Table('order', metadata, autoload=True, autoload_with=engine)
property_type=Table('property_type', metadata, autoload=True, autoload_with=engine)
room_type=Table('room_type', metadata, autoload=True, autoload_with=engine)
user=Table('user', metadata, autoload=True, autoload_with=engine)

## AttributeError

Начнем с ошибки типа *AttributeError*, которая возникает при попытке доступа к несуществующему атрибуту, например, к столбцу, которого нет. Чтобы продемонстрировать ошибку этого типа, выполним запрос к таблице пользователей. Затем попытаемся получить доступ к столбцу, который не был выбран в запросе.

In [96]:
# 4-1. Выполнение приводит к ошибке.

s=select([user.c.user_name, user.c.phone])
results=connection.execute(s)
for result in results:
    print(result.phone)
    print(result.password)

+7-929-616-88-77


AttributeError: Could not locate column in row for column 'password'

В сообщении об ошибке указан тип ошибки `AttributeError`,<br> отмечена строка, в которой произошла ошибка `----> 7`,<br> приводится сообщение о причине ошибки `AttributeError: Could not locate column in row for column 'password'`<br><br>
Тип ошибки *AttributeError* может встречаться в программах на Пайтон и без использования SQLAlchemy. Однако, встречаются и специфичные для SQLAlchemy ошибки. К таким относятся ошибки типа *IntegrityError*.

## IntegrityError

Другой распространенной ошибкой SQLAlchemy является ошибка типа IntegrityError, которая возникает, когда мы пытаемся сделать что-то, что нарушило бы ограничения. Например, при попытке создать двух пользователей с одним и тем же именем пользователя будет выдано *IntegrityError*, потому что имена пользователей должны быть уникальными. В следующем примере показан код, вызывающий такую ошибку. Распечатаем имена всех пользователей.

In [97]:
s=select([user.c.user_name])
connection.execute(s).fetchall()

[('Ivan',), ('Lida',), ('Nicolas',), ('Svetlana',), ('Vera',)]

Теперь добавим запись с именем уже существующего пользователя, что должно вызвать ошибку, так как имена пользователей должны быть уникальными.

In [98]:
ins=insert(user).values(
    user_name='Ivan',
    email_address='adrr@server.com',
    phone='+7-999-222-44-77',
    password='D@%%ffsh554'
)
print(str(ins))
print(ins.compile().params)

INSERT INTO "user" (user_name, email_address, phone, password) VALUES (:user_name, :email_address, :phone, :password)
{'user_name': 'Ivan', 'email_address': 'adrr@server.com', 'phone': '+7-999-222-44-77', 'password': 'D@%%ffsh554'}


`# 4-2`<br>
`result=connection.execute(ins)`

Выполнение этой команды вызывает ошибку *IntegrityError*

```
---------------------------------------------------------------------------
IntegrityError                            Traceback (most recent call last)
~\anaconda3\lib\site-packages\sqlalchemy\engine\base.py in _execute_context(self, dialect, constructor, statement, parameters, *args)
   1245                     self.dialect.do_execute(
-> 1246                         cursor, statement, parameters, context
   1247                     )

~\anaconda3\lib\site-packages\sqlalchemy\engine\default.py in do_execute(self, cursor, statement, parameters, context)
    587     def do_execute(self, cursor, statement, parameters, context=None):
--> 588         cursor.execute(statement, parameters)
    589 

IntegrityError: UNIQUE constraint failed: user.user_name
```

Получено сообщение о нарушении условия уникальности поля *user_name*

`IntegrityError: UNIQUE constraint failed: user.user_name`

Хотя существует множество других ошибок, эти две являются наиболее распространенными. Больше об ошибках в документации SQLAlchemy:
- http://docs.sqlalchemy.org/en/latest/core/exceptions.html
- https://docs.sqlalchemy.org/en/14/errors.html#error-gkpj. 

Поскольку мы не хотим, чтобы наши программы аварийно завершали работу при обнаружении ошибки, нам необходимо научиться правильно обрабатывать ошибки.

## Обработка ошибок

Чтобы предотвратить сбой или остановку нашей программы из-за ошибки, необходимо аккуратно обрабатывать ошибки. Мы можем сделать это так же, как и с любой ошибкой Python, с помощью блока *try .. except*. Например, мы можем использовать блок *try .. except*, чтобы отловить ошибку и распечатать сообщение об ошибке, а затем продолжить выполнение остальной части нашей программы.

In [99]:
from sqlalchemy.exc import IntegrityError

In [100]:
ins = insert(user).values(
    user_name="Ivan",
    email_address="adrr@server.com",
    phone="+7-999-222-44-77",
    password="D@%%ffsh554")

In [101]:
# 4-3

try:
    result = connection.execute(ins)
except IntegrityError as error:
    print(error.orig)
    print(error.statement)
    print(error.params)

print("Программа продолжила работу")

UNIQUE constraint failed: user.user_name
INSERT INTO user (user_name, email_address, phone, password) VALUES (?, ?, ?, ?)
('Ivan', 'adrr@server.com', '+7-999-222-44-77', 'D@%%ffsh554')
Программа продолжила работу


В примере 4-3 мы поместили выражение внутрь *try .. exept*, поймали ошибку и распечатали сообщение об ошибке, после чего программа продожила работу.

Необходимо стремиться к тому, чтобы заключать как можно меньше кода в блок *try.. except* и выявлять только определенные ошибки. Это предотвращает обнаружение неожиданных ошибок, поведение которых действительно должно отличаться от поведения обнаружения конкретной ошибки, которую вы наблюдаете.

Хотя мы смогли обработать это исключение с помощью традиционных инструментов Python, сам по себе этот метод не сработает, если у нас есть несколько операторов базы данных, которые зависят друг от друга. В таких случаях нам нужно заключить эти операторы в транзакцию базы данных. SQLAlchemy предоставляет для этой цели оболочку, встроенную в объект подключения: транзакции.

## Транзакции

Вместо того, чтобы глубоко изучать теорию баз данных, лежащую в основе транзакций подумаем о транзакциях как о способе гарантировать, что несколько операторов базы данных будут успешными или неудачными как группа. Когда мы начинаем транзакцию, мы записываем текущее состояние нашей базы данных; тогда мы можем выполнить несколько операторов SQL. Если все операторы SQL в транзакции завершаются успешно, база данных продолжает работу в обычном режиме, и мы отменяем предыдущее состояние базы данных. Однако, если один или несколько из этих операторов не срабатывают, мы можем отловить эту ошибку и использовать предыдущее состояние для отката любых успешных операторов. На рисунке 4-1 показаны нормальный рабочий процесс транзакции и процесс возврата к предыдущему состоянию из-за возникшей в процессе транзакции ошибки.

<img src="../Img/Transactions.png">
Рис. 4.1. Процессы транзакции

Создадим транзакцию нового заказа. Для создания нового заказа требуется заполнение таблиц заказов *order* и строк заказа *line_item*. Сначала узнаем максимальные значения идентификаторов в обоих таблицах.  

In [103]:
from sqlalchemy.sql import func

s=select([func.max(order.c.order_id)])
rp=connection.execute(s).scalar()
max_order_id = rp
print(f'Макс. значение индекса заказа: {max_order_id}')

s=select([func.max(line_item.c.line_item_id)])
rp=connection.execute(s).scalar()
max_line_id = rp
print(f'Макс. значение индекса строки заказа: {max_line_id}')

Макс. значение индекса заказа: 5
Макс. значение индекса строки заказа: 4


Создадим условие нового заказа

In [104]:
new_order_id = max_order_id + 1
ins_order = insert(order)
ins_order = ins_order.values((new_order_id, 1, True, 250))

print(str(ins_order))
print(ins_order.compile().params)

INSERT INTO "order" (order_id, user_id, confirmed, order_price) VALUES (:order_id, :user_id, :confirmed, :order_price)
{'order_id': 6, 'user_id': 1, 'confirmed': True, 'order_price': 250}


Создадим детали нового заказа. Специально присвоим идентификатору строки заказа число 1

`.values((1, new_order_id, ... `

что будет явным нарушением целостности, так как такое значение в таблице *line_item* уже есть.

In [105]:
ins_line = insert(line_item)
ins_line = ins_line.values((1, new_order_id, 31080, datetime.strptime('2021.03.01','%Y.%m.%d'),
                datetime.strptime('2020.03.17','%Y.%m.%d'))) # Такой индекс строки уже есть

print(str(ins_line))
print(ins_line.compile().params)

INSERT INTO line_item (line_item_id, order_id, listing_id, item_start_date, item_end_date) VALUES (:line_item_id, :order_id, :listing_id, :item_start_date, :item_end_date)
{'line_item_id': 1, 'order_id': 6, 'listing_id': 31080, 'item_start_date': datetime.datetime(2021, 3, 1, 0, 0), 'item_end_date': datetime.datetime(2020, 3, 17, 0, 0)}


Добавим заказ и его детали в рамках одной транзакции

In [106]:
transaction = connection.begin()

rp = connection.execute(ins_order)

try:
    rp = connection.execute(ins_line)
    
except IntegrityError as error:
    transaction.rollback()
    print(error)

(sqlite3.IntegrityError) UNIQUE constraint failed: line_item.line_item_id
[SQL: INSERT INTO line_item (line_item_id, order_id, listing_id, item_start_date, item_end_date) VALUES (?, ?, ?, ?, ?)]
[parameters: (1, 6, 31080, '2021-03-01 00:00:00.000000', '2020-03-17 00:00:00.000000')]
(Background on this error at: https://sqlalche.me/e/14/gkpj)


Добавление новой записи в таблицу *order* не вызвало ошибки, однако добавление новой записи в таблицу *line_item* вызвало ошибку из-за повторяющегося значения первичного ключа.

Так как мы попытались добавить в таблицу деталей заказа *line_item* новую строку с нарушением целостности в части повторения значения первичного ключа, то управление программой перешло в раздел исключений блока *try.. exept*, где произошел откат транзакции к состоянию, предшествующему всем изменениям. Максимальные значения идентификатора заказа и строки заказа не изменились.

In [107]:
s1=select([func.max(order.c.order_id)])
s2=select([func.max(line_item.c.line_item_id)])

print(connection.execute(s1).scalar(), connection.execute(s2).scalar())

5 4


На этом занятии мы узнали, как обрабатывать исключения как для отдельных операторов, так и в группах операторов. Используя обычный блок *try .. except* для одного оператора, мы можем предотвратить сбой нашего приложения в случае ошибки оператора базы данных. Мы также рассмотрели, как транзакции могут помочь нам избежать сбоев приложения в группах операторов. Далее узнаем, как протестировать наш код, чтобы убедиться, что он ведет себя так, как мы ожидаем.

<a id=T_5_5></a>
# 5.5. Отображение
[<= ](#T_5_4)||[ К оглавлению ](#Ref)||[ =>](#T_5_6)



## Отображение отдельной таблицы

Отображение - это метод, который позволяет нам заполнять объект SQLAlchemy из существующей базы данных. Вы можете отражать таблицы, представления, индексы и внешние ключи. Для изучения этой функциональности используем базу данных Чайнук http://chinookdatabase.codeplex.com/. Нам понадобятся объкты *metadata* и связанный с базой данных движок *engine*.

In [109]:
# 5-1

from sqlalchemy import MetaData, Table, create_engine, select
metadata = MetaData()
engine = create_engine('sqlite:///../Data/Chinook_Sqlite.sqlite')

connection=engine.connect()

Создание объекта таблиц *artist* и *album*. Аргументы *autoload* и *autoload_with* необходимы для отображения информации из схемы базы данных на объект *metadata* и хранения ссылки на таблицу в переменных *artist* и *album*.

In [110]:
# 5-2

artist = Table('artist', metadata, autoload=True, autoload_with=engine)
album = Table('album', metadata, autoload=True, autoload_with=engine)

Распечатаем информацию о полях *artist*

In [111]:
artist.columns.keys()

['ArtistId', 'Name']

Выполним запрос

In [112]:
# 5-3

s = select([artist]).limit(10)
engine.execute(s).fetchall()

[(1, 'AC/DC'),
 (2, 'Accept'),
 (3, 'Aerosmith'),
 (4, 'Alanis Morissette'),
 (5, 'Alice In Chains'),
 (6, 'Antônio Carlos Jobim'),
 (7, 'Apocalyptica'),
 (8, 'Audioslave'),
 (9, 'BackBeat'),
 (10, 'Billy Cobham')]

Проверим метаданные таблицы *album*, чтобы увидеть, что именно отразилось.

In [113]:
metadata.tables['album']

Table('album', MetaData(), Column('AlbumId', INTEGER(), table=<album>, primary_key=True, nullable=False), Column('Title', NVARCHAR(length=160), table=<album>, nullable=False), Column('ArtistId', INTEGER(), table=<album>, nullable=False), schema=None)

Отметим, что информация о внешнем ключе отстутсвует. Проверим атрибут *foreign_keys* таблицы *album*, чтобы убедиться, что его действительно нет.

In [114]:
album.foreign_keys

set()

Восстановим отношение.

In [115]:
# 5-4

from sqlalchemy import ForeignKeyConstraint
album.append_constraint(
    ForeignKeyConstraint(['ArtistId'], ['artist.ArtistId'])
)

In [116]:
metadata.tables['album']

Table('album', MetaData(), Column('AlbumId', INTEGER(), table=<album>, primary_key=True, nullable=False), Column('Title', NVARCHAR(length=160), table=<album>, nullable=False), Column('ArtistId', INTEGER(), ForeignKey('artist.ArtistId'), table=<album>, nullable=False), schema=None)

Теперь используем соединение *join*

In [117]:
join_expression = artist.join(album, album.c.ArtistId == artist.c.ArtistId)
str(join_expression)

'artist JOIN album ON album."ArtistId" = artist."ArtistId"'

Теперь мы можем выполнять запросы, использующие отношения.

In [118]:
def find_album(artist_name):
    sel=select([album.columns.Title])
    sel=sel.select_from(album.join(artist))
    sel=sel.where(artist.columns.Name == artist_name)
    
    return connection.execute(sel).fetchall()

In [119]:
print(find_album("Santana"))
print(find_album("AC/DC"))

[('Supernatural',), ('Santana - As Years Go By',), ('Santana Live',)]
[('For Those About To Rock We Salute You',), ('Let There Be Rock',)]


Было бы довольно сложно повторить процесс отражения для каждой отдельной таблицы в базе данных. К счастью, SQLAlchemy позволяет отображать всю базу данных сразу.

## Отображение базы данных

Для отображения базы данных целиком необходимо использовать метод *reflect* объекта *metadata*. В отличие от отображений отдельных таблиц, в отображении базы данных сохраняется информация о внешних ключах.

In [120]:
metadata.reflect(bind=engine)

Этот оператор ничего не возвращает в случае успеха; однако мы можем запустить следующий код, чтобы получить список имен таблиц, чтобы увидеть, что было отражено в метаданных

In [121]:
metadata.tables.keys()

dict_keys(['artist', 'album', 'Album', 'Artist', 'Customer', 'Employee', 'Genre', 'Invoice', 'InvoiceLine', 'Track', 'MediaType', 'Playlist', 'PlaylistTrack'])

Теперь используем отображенные таблицы в запросах.

## Построение запросов с использованием отображенных объектов

Чтобы использовать таблицы в запросах, как это было сделано ранее в примере 5-3, необходимо иметь способ ссылаться на них. Мы можем сделать это, назначив их переменной из атрибута таблицы метаданных.

In [122]:
# 5-5

playlist = metadata.tables['Playlist']

s = select([playlist]).limit(10)
engine.execute(s).fetchall()

[(1, 'Music'),
 (2, 'Movies'),
 (3, 'TV Shows'),
 (4, 'Audiobooks'),
 (5, '90’s Music'),
 (6, 'Audiobooks'),
 (7, 'Movies'),
 (8, 'Music'),
 (9, 'Music Videos'),
 (10, 'TV Shows')]