

<FloatPosing>:
    orientation: 'vertical'
    Button:
        size_hint: 0.3, 0.3
        pos: 100, 100 #расположение элементов, не адаптивно
        pos_hint: {'center_x': 0.5, 'top': 1} #по х - центр и прилеплена по y к вверху
        text: 'First'

    Button:
        size_hint: 0.2, 0.2
        pos_hint: {'center_x': 0.5, 'center_y': 0.5} #адаптивное расположение по центру
        text: 'Second'